### 1D array operations 

#### Create

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Created Array:", arr)

Created Array: [1 2 3 4 5]


#### Insert

In [8]:
arr = np.insert(arr, 2, 10)
print("Array after insertion:", arr)

Array after insertion: [ 1  2 10  3  4  5]


 #### Update

In [9]:
arr[1] = 20
print("Array after update:", arr)

Array after update: [ 1 20 10  3  4  5]


####  Iterate

In [10]:
print("Iterating through the array:")
for element in arr:
    print(element)

Iterating through the array:
1
20
10
3
4
5


#### Delete

In [11]:
arr = np.delete(arr, 3)
print("Array after deletion:", arr)

Array after deletion: [ 1 20 10  4  5]


#### Search

In [12]:
element_to_search = 20
index = np.where(arr == element_to_search)[0]
if len(index) > 0:
    print(f"Element {element_to_search} found at index {index[0]}")
else:
    print(f"Element {element_to_search} not found in the array")

Element 20 found at index 1


#### Count 

In [13]:
element_to_count = 20
count = np.count_nonzero(arr == element_to_count)
print(f"Count of {element_to_count} in the array: {count}")

Count of 20 in the array: 1


In [14]:
count=0
for elements in arr:
    count=count+1
print(f"There is the {count} number of element present in array")

There is the 5 number of element present in array


### 2D array operations

#### Create

In [15]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("2D Array:")
print(arr_2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Insert 

In [16]:
arr_2d = np.insert(arr_2d, 1, 10, axis=1)

print("2D Array after insertion:")
print(arr_2d)

2D Array after insertion:
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


#### Update 

In [17]:
arr_2d[1, 2] = 30

print("2D Array after update:")
print(arr_2d)

2D Array after update:
[[ 1 10  2  3]
 [ 4 10 30  6]
 [ 7 10  8  9]]


#### Iterate

In [18]:
print("Iterating through 2D array:")
for row in arr_2d:
    for element in row:
        print(element)

Iterating through 2D array:
1
10
2
3
4
10
30
6
7
10
8
9


#### Delete

In [19]:
arr_2d = np.delete(arr_2d, 2, axis=0)

print("2D Array after deletion:")
print(arr_2d)

2D Array after deletion:
[[ 1 10  2  3]
 [ 4 10 30  6]]


#### Search 

In [20]:
element_to_search = 30
index = np.where(arr_2d == element_to_search)
print(f"Element {element_to_search} found at indices {index}")

Element 30 found at indices (array([1], dtype=int64), array([2], dtype=int64))


#### Count 

In [21]:
element_to_count = 10
count = np.count_nonzero(arr_2d == element_to_count)
print(f"Count of {element_to_count} in the 2D array: {count}")

Count of 10 in the 2D array: 2


In [22]:
count = 0
for row in arr_2d:
    for element in row:
        count += 1

print(f"There are {count} elements present in the 2D array.")

There are 8 elements present in the 2D array.


### 3D array operations

#### Create

In [23]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])

print("3D Array:")
print(arr_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


#### Insert 

In [24]:
arr_3d = np.insert(arr_3d, 1, 20, axis=2)

print("3D Array after insertion:")
print(arr_3d)

3D Array after insertion:
[[[ 1 20  2  3]
  [ 4 20  5  6]]

 [[ 7 20  8  9]
  [10 20 11 12]]

 [[13 20 14 15]
  [16 20 17 18]]]


#### Update 

In [25]:
arr_3d[0, 1, 2] = 30

print("3D Array after update:")
print(arr_3d)

3D Array after update:
[[[ 1 20  2  3]
  [ 4 20 30  6]]

 [[ 7 20  8  9]
  [10 20 11 12]]

 [[13 20 14 15]
  [16 20 17 18]]]


####  Iterate

In [26]:
print("Iterating through 3D array:")
for matrix in arr_3d:
    for row in matrix:
        for element in row:
            print(element)

Iterating through 3D array:
1
20
2
3
4
20
30
6
7
20
8
9
10
20
11
12
13
20
14
15
16
20
17
18


#### Delete

In [27]:
arr_3d = np.delete(arr_3d, 1, axis=1)

print("3D Array after deletion:")
print(arr_3d)

3D Array after deletion:
[[[ 1 20  2  3]]

 [[ 7 20  8  9]]

 [[13 20 14 15]]]


#### Search 

In [28]:
element_to_search = 30
index = np.where(arr_3d == element_to_search)
print(f"Element {element_to_search} found at indices {index}")

Element 30 found at indices (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


#### Count 

In [29]:
element_to_count = 20
count = np.count_nonzero(arr_3d == element_to_count)
print(f"Count of {element_to_count} in the 3D array: {count}")

Count of 20 in the 3D array: 3


In [30]:
count = 0
for matrix in arr_3d:
    for row in matrix:
        for element in row:
            count += 1

print(f"There are {count} elements present in the 3D array.")

There are 12 elements present in the 3D array.


### Functions for array manipulation

In [31]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr1=np.flip(arr)
arr1

array([[6, 5, 4],
       [3, 2, 1]])

In [33]:
arr2=np.rot90(arr,k=1)
arr2

array([[3, 6],
       [2, 5],
       [1, 4]])

In [34]:
arr2=np.rot90(arr,k=2)
arr2

array([[6, 5, 4],
       [3, 2, 1]])

In [35]:
arr3=np.ravel(arr)
print(arr3)

[1 2 3 4 5 6]


In [36]:
arr3=np.ravel(arr)
arr3

array([1, 2, 3, 4, 5, 6])

In [37]:
arr4=arr.flatten()
arr4

array([1, 2, 3, 4, 5, 6])

In [38]:
for x in np.nditer(arr1):
    print(x)

1
2
3
4
5
6


In [39]:
a=np.array([3,7,1,9,3])
arr5=np.sort(a)
arr5

array([1, 3, 3, 7, 9])

In [40]:
a=np.array([3,7,1,9,3])
arr5=np.sort(a)[::-1]
arr5

array([9, 7, 3, 3, 1])

In [41]:
a=np.array([3,7,1,9,3])
arr5=np.sort(a)[-1::-1]
arr5

array([9, 7, 3, 3, 1])

In [42]:
a=np.array([3,7,1,9,3])
arr5=np.sort(a)[-1:-6:-1]
arr5

array([9, 7, 3, 3, 1])

In [43]:
arr2d=a[:,np.newaxis]
arr2d

array([[3],
       [7],
       [1],
       [9],
       [3]])

In [44]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr3d=arr_1d.reshape((2,2,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = arr_2d.reshape((1, 3, 3))
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
import numpy as np
my_array = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
letter_to_check = 'c'
positions = np.where(my_array == letter_to_check)[0]
result = np.isin(np.arange(len(my_array)), positions)
print(result)

[False False  True False False False]


In [47]:
txt = "Hello, welcome to my world."

x = txt.index("welcome")

print(x)

7
