In [1]:
import numpy as np

# Creating Universal Function

In [2]:
def universal_function(arr1, arr2):
    result = np.add(arr1, arr2)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)

[5 7 9]


In [3]:
type(result_array)

numpy.ndarray

In [4]:
type(universal_function)

function

# Inbuilt Function

In [5]:
def universal_function(arr1, arr2):
    result = np.subtract(arr1, arr2)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)


[-3 -3 -3]


In [6]:
def universal_function(arr1, arr2):
    result = np.exp(arr1)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)

[ 2.71828183  7.3890561  20.08553692]


In [7]:
def universal_function(arr1, arr2):
    result = np.log(arr1)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)

[0.         0.69314718 1.09861229]


In [8]:
def universal_function(arr1, arr2):
    result = np.sin(arr1)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)

[0.84147098 0.90929743 0.14112001]


In [9]:
def universal_function(arr1, arr2):
    result = np.cos(arr1)
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
print(result_array)

[ 0.54030231 -0.41614684 -0.9899925 ]


# Operations On Universal Function

# 1.Arithmetic Operations

In [10]:
import numpy as np
def universal_function(arr1, arr2):
    result = np.add(np.multiply(arr1, 2), np.subtract(arr2, 1))
    return result
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = universal_function(array1, array2)
squared_result = np.square(result_array)
sum_result = np.sum(result_array)
mean_result = np.mean(result_array)
print("Original Result:", result_array)
print("Squared Result:", squared_result)
print("Sum of Result:", sum_result)
print("Mean of Result:", mean_result)

Original Result: [ 5  8 11]
Squared Result: [ 25  64 121]
Sum of Result: 24
Mean of Result: 8.0
